---
title: "Math 456 Daily Schedule (subject to adjustment)"
output: 
  html_document: 
    theme: journal
---

```{r include = FALSE}
library(dplyr)
library(stringr)
library(readr)
```

```{r results="asis", echo=FALSE}
source("C:/Github/MATH456/stylesheets/custom.R")
```

Navbar: [[Home]](index.html) [[Data]](./data/Datasets.html) [[HW Info]](HW_Info.html)  [[Google Group]](https://groups.google.com/forum/#!forum/csuc_stat)  [[Google Drive]](https://drive.google.com/a/mail.csuchico.edu/folderview?id=0B83Z8_sNw3KPcnVrYzVFRHUtcHM&usp=sharing)


```{r include = FALSE}
rawdat <- read_csv(file.path("admin", "lecture-notes.csv"))
cdat   <- rawdat %>% mutate(Date = format(as.Date(date, "%m/%d/%Y"), "%m/%d"), 
                            Outline = ifelse(grepl("^wk", Week) & Outline != "",
                                      sprintf("%s: %s", Week, Outline), Outline)) 

# Link to weekly topic outline
cmdat <- data_frame(html = list.files(pattern = '^wk.*html$'))
cmdat <- cmdat %>% mutate(Week = str_replace(html, ".html", ""))
cdat  <- cdat %>% full_join(cmdat)

cdat$topic[cdat$link_it] <- str_replace(cdat$Outline[cdat$link_it], "(.*:)", '<a href="LINK">\\1</a>')
cdat$Topic <- ifelse(cdat$link_it,  str_replace(cdat$topic, "LINK", cdat$html), cdat$Outline)
cdat <- cdat[,c('Week', 'Day', 'Date', 'Topic', 'raw_notes', 'Evaluations', 'link_it')]

# Add direct links to notes
lmdat <- data_frame(html = list.files(path="notes/", pattern = '^lec.*html$'))
lmdat <- lmdat %>% mutate(raw_notes = str_replace(html, ".html", ""), 
                          link = paste("notes/", html, sep=""))
lcdat <- cdat %>% left_join(lmdat)

lcdat$notes[lcdat$link_it] <- str_replace(lcdat$raw_notes[lcdat$link_it], "(.*)", '<a href="LINK">\\1</a>')
lcdat$Notes <- ifelse(lcdat$link_it,  str_replace(lcdat$notes, "LINK", lcdat$link), lcdat$raw_notes)
clean <- lcdat %>% mutate(Topic=ifelse(is.na(Topic), '-', Topic), 
                          Notes=ifelse(is.na(Notes), '-', Notes),
                          Evaluations=ifelse(is.na(Evaluations), '-', Evaluations))

clean <- clean[,c('Date', 'Day', 'Topic', 'Notes', 'Evaluations')]
```

<!-- unholy hack to make following two tables less wide and the same wide -->
<style type="text/css">
table {
   max-width: 50%;
}
</style>


```{r results = 'asis', echo = FALSE}
knitr::kable(clean)
```
