---
title: "California State University Chico \n Department of Mathematics and Statistics"
output:
  html_document:
    highlight: pygments
  pdf_document: default
---

# MATH 456, Applied Statistics II, Section 01, Spring 2016

### Course Information
**Instructor:** Dr. Robin Donatello  
**Office Location:** Holt 216  
**Telephone:** 898-5767  
**E-mail:** rdonatello@csuchico.edu  
**Office Hours:** TBD Week 2
**Class days and times:** MWF 2-2:50, Holt 155  
**Prerequisites:** MATH 315/615 at Chico State or instructor permission.  
**Course Website:** http://norcalbiostat.github.io/MATH456/  
**Piazza Forum:** https://piazza.com/mail.csuchico.edu/spring2016/math456

## Course Description and Goals
From the CSUC Course Catalog: Advanced topics in applied statistics including multiple regression, multivariate methods, nonparametrics, analysis of covariance, bootstrap methods and others as appropriate. Statistical computer packages are introduced and used. Appropriate for biology, agriculture, nutrition, business, psychology, social science and other maojrs. 3 hours discussion.


## Course Content Learning Outcomes
Upon successful completion of this course, students will be able to:  

* Translate a research question into an appropriate statistical analysis plan. 
* Prepare data for analysis by cleaning and transforming raw data. 
* Perform research in a reproducible manner. 
* Build statistical models to examine real processes. 
* Report the results of the analysis in plain language. 


## Required Materials
#### Textbooks
Practical Multivariate Analysis 5th Edition. Afifi, May, Clark ISBN 9781439816806  
You can use the promo code **LEARN** at www.crcpress.com  to save 25% off of the textbook or any other CRC Press book they need for the semester. This special, student discount is only available through this offer for the upcoming spring semester.

#### Computer Hardware and Software 
We will be using the statistical programming language R. You are expected to have prior experience with this language. 
Loaner laptops will be available for you to use during class time only. These systems will be set up properly and ready to go on day 1. You will eventually have to set up and bring your own laptop to class. There will not be sufficient time during class for you to complete the necessary work. All software programs we will use are free.  

Download and install the following software within the first two weeks of class.

  - **R** http://cran.r-project.org/
  - **R-Studio** http://www.rstudio.com/products/rstudio/download/
  - **The typesetting environment LaTeX** http://www.latex-project.org/

Here is a [slide deck](notes/xtra01_InstallPrograms.html) containing instructions on how to install R and R Studio. _Notes are currently from a different class, the Swirl lessons are not needed in this class_. 


**If you have no prior experience with R you have some choices.**

1) Go through any number of self-paced free online tutorials. Recommended ones are [DataCamp](https://www.datacamp.com/courses/free-introduction-to-r), [TryR](http://tryr.codeschool.com/), and [R Tutorial](http://www.r-tutor.com/r-introduction).    
2) Go through a self-paced online R Bootcamp specifically designed by Dr. Donatello to provide just the basics needed for coursework in this class. This includes an introduction to Markdown. This Bootcamp can be found at http://norcalbiostat.github.io/R-Bootcamp/
3) Plan on enrolling in the in-person version of this R Bootcamp at the start of the semester. This will be 2 hour classes, 2 nights/week, for the first 3 weeks. Specific enrollment details will be announced as they are finalized. 

## Online Component
* All course materials can be found on the [course website](http://norcalbiostat.github.io/MATH456/).  
* We will use Google Drive for assignment submission. Grade records may or may not be done via BBLearn.   
* We will be using [Piazza](https://piazza.com/mail.csuchico.edu/spring2016/math456) as the place for discussion outside of class.   
* You are responsible for regularly checking Piazza for updates and announcements.  
* The daily class schedule can be found on the class website [here](Schedule.html).  
* It is your responsibility to be aware of the current schedule.  


## Assignments and Grading Policy
Practice problems will be assigned regularly and will be worked on during and outside of class time. An open note quiz will be administered at appropriate intervals, typically a day or two after a section or topic has been completed. Quiz questions will directly come from the practice problems, so it is in your best interest to have all problems completed and well-organized. 

You will also be expected to participate in discussions during class, and outside of class on the forum board. 

No Late work accepted without prior approval. 

**Weights**:  Quizzes 15%; Participation 15%; Homework 20%; Midterm Report 25%; Final Report 25%  
**Letter grade**: A [95-100), A- [90-94), B+ [87, 89), B [83-86), B- [80, 82), C+ [77-79), C [73-76), C- [79, 72), D+ [65, 69), D [60, 64), F < 60


### Time Commitment
CSUC and Federal policy states that "One hour of classroom or direct faculty instruction and a minimum of two hours of out-of-class student work each  week for approximately fifteen weeks for one semester hour of credit".  

It is not easy to write literate computer programs but the payoff is immeasurable. You will spend 3 hours in class discussing topics and working on code. Expect to spend around 6 hours outside of class to read, write, code and problem solve. For the best chance of success start assignments early, use the discussion forms, form study groups and come to office hours. You will get out of this class what you put into it.

Completing the required readings and starting to work out problems in R prior to class time will make for a much more productive and useful class meeting time. We only have 50 minutes face to face, plan on making the most of it. 

## Getting Help
* Your first resource is each other. 
* Use the class [Piazza](https://piazza.com/mail.csuchico.edu/spring2016/math456) forum for R and Markdown debugging problems.
* Come to the RUG meetings / open work sessions. 
* I will **not** answer emails about any coding problems. Check the class discussion forum for a solution first. 
* Another great resource is [StackOverflow](http://stackoverflow.com/questions/tagged/r) using the `r` or `markdown` tags. 
* Prepare a [minimal working example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) of your problem on the forum, it may be helpful to include a screenshot of the problem. 



## University Policies and Campus Resources

## Dropping and Adding
The last day to drop or add a course is 2/19/16. After this date, withdraws will only be allowed for serious and compelling reasons subject to department approval. You are responsible for understanding the policies and procedures about add/drops, academic renewal, etc., found in the CSU Chico University Catalog.  You should be aware of the new deadlines and penalties for adding and dropping classes. 

### Academic Integrity
Students are expected to be familiar with the University's Academic Integrity Policy. Your own commitment to learning, as evidenced by your enrollment at California State University, Chico, and the University's Academic Integrity Policy requires you to be honest in all your academic course work. Faculty members are required to report all infractions to the Office of Student Judicial Affairs. The policy on academic integrity and other resources related to student conduct can be found on the  Student Judicial Affairs web site.

## Plagerism
Working with others is expected, directly copying code and interpretations is not. Plagerism is completely unacceptable and very easily detected. Will result in 0 credit for all parties if observed. Does nothing but make it harder to understand the material and pass the class


### IT Support Services
Computer labs for student use are located on the first and fourth floor of the Meriam Library, Room 116 and 450, Tehama Hall Room 131, and the Bell Memorial Union (BMU) basement. You can get help using your computer from IT Support Services; contact them through the ITSS web site. There are loaner laptops available _during class time only_ in Holt 155. 

### Americans with Disabilities Act
If you need course adaptations or accommodations because of a disability or chronic illness, or if you need to make special arrangements in case the building must be evacuated, please make an appointment with me as soon as possible, or see me during office hours. Please also contact Accessibility Resource Center (ARC) as they are the designated department responsible for approving and coordinating reasonable accommodations and services for students with disabilities. ARC will help you understand your rights and responsibilities under the Americans with Disabilities Act and provide you further assistance with requesting and arranging accommodations. Phone: 530-898-5959. Location: Student Services Center 170. Email: arcdept@csuchico.edu

### Student Learning Center
The mission of the Student Learning Center (SLC) is to provide services that will assist CSU, Chico students to become independent learners. The SLC prepares and supports students in their college course work by offering a variety of programs and resources to meet student needs. Specific of note for this course is that the University Writing Center has been combined with the Student Learning Center. It is advised that you utilize these services to continually improve your writing skills and habits. 



