---
title: "Week 1 - Wednesday "
author: "MATH 456, Spring 2016"
date: "1/27/16"
output: 
  html_document: 
    theme: journal
---

# Announcements


# Prepare (Before class)
* Create a MATH456 folder in an easy to find place on your computer or flash drive. All files related to this class will go in there.
    - Create a sub-folder in here, called DATA. You can guess what will go in here. 
* Read Guide to sharing data by Jeff Leek: https://github.com/jtleek/datasharing
* The spreadsheet error and austerity - as seen through [The Colbert Report](http://thecolbertreport.cc.com/videos/kbgnf0/austerity-s-spreadsheet-error---thomas-herndon)'s eyes. Moral of this story: ask for the data and question results that look too good to be true. 

# Notes
* Preparing data for Analysis [[HTML]](notes/lec02_data_prep.html)[[PDF]](notes/lec02_data_prep.pdf)


# Experience (During Class)
Cleaning up US Census data. 

# Data (as needed)
* Rates of Poverty in CA: https://cdph.data.ca.gov/Demographics/Poverty-Rate-defined-by-U-S-Census-by-California-R/pbut-di2i


# Practice (After Class)


## Additional articles of note regarding reproducible research and common data errors
In reverse chronological order

* http://simplystatistics.org/2014/06/06/the-real-reason-reproducible-research-is-important/
* http://www.nature.com/news/how-scientists-fool-themselves-and-how-they-can-stop-1.18517
* http://simplystatistics.org/2015/10/20/we-need-a-statistically-rigorous-and-scientifically-meaningful-definition-of-replication/
* Special articles in Nature http://www.nature.com/news/reproducibility-1.17552 that talk about the need to share code and reproducibility in the sciences. 


### The cancer research scandal at Duke. 
Simple and not so simple erorrs, combined with some fradulent cover-up puts cancer patient's lives at risk. 

* [60 minutes story](https://www.youtube.com/watch?v=eV9dcAGaVU8)
* [60 min interview with Baggerly](https://www.youtube.com/watch?v=66dPIFMJ_-A)
* [A biostatisticans telling of the tale](https://uw.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=bc239422-6a6e-4854-a4c7-37edcd54e9a0) Skip to 1:12 for the start. 
* [Kieth Baggerly](https://uw.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=6760b204-c935-4e33-b93d-61530135f171) talking about reproducible research and big data (such as genomic type data), and what can go wrong. This is the long version, but straight from the man himself. 

