---
title: "Week 1"
author: "MATH 459, Spring 2016"
date: ' 1/25/16'
output: html_document
---
```{r results="asis", echo=FALSE}
#source("~/Github/MATH456/stylesheets/custom.R")
source("C:/Github/MATH456/stylesheets/custom.R")
```
[[Schedule]](Schedule.html) [[Week 2]](wk02.html)

## Announcements
Welcome to MATH 456 - Applied Statistics II

### Notes and Materials
* lec00: Intro to the Class [[PDF]](notes/lec00_Intro.pdf)[[HTML]](notes/lec00_Intro.html)
* The class [Syllabus](./Syllabus.html). 
* lec01: Preparing Data for Analysis [[PDF]](notes/lec01_data_prep.pdf)[[HTML]](notes/lec01_data_prep.html)


## Experience (During Class)
### Monday
**In class:**

* Class logistics, preliminaries, expecations, syllabus
* Review of webpage layout and location of course materials
* Group assignments, seating and screen viewing logistics
* Introduction to the Question Formulation Technique (QFT)


### Wednesday
**Prepare:**  

* Download and install R and R studio  
    - You can find a set of slides on how to install both [here](http://htmlpreview.github.io/?https://github.com/norcalbiostat/R-Bootcamp/blob/gh-pages/lecture_notes/0_2_-_Setup_R_and_R_Studio.html) 
    - note that these slides are from a different class. These slides also contain links to You Tube videos that can help you with these installations.
    - Don't worry about the swirl lessons. They will not be used for this class. 
* Review [lec01](notes/lec01_data_prep.html) notes.    
* We will be starting to use R and Markdown at the same time tomorrow. If you have never used Markdown then you are advised to  
    - Follow along with this 6 minute tutorial https://www.youtube.com/watch?v=DNS7i2m4sB0 
    - Review the basics of the markdown syntax in this 2 minute video https://www.youtube.com/watch?v=Nc0CS0nX-M4
* Complete Afifi problem 2.5. I have scanned Afifi chapter 2 and 3 - this PDF can be found in the shared Google Drive. If you do not have access please email me. 

**In class:**

* Discuss and share answers to Afifi Problem 2.5
* Preparing Data for Analysis
    - Characterizing Data for Analysis (Ch 2)
    - Data wrangling, munging, recoding, editing, cleaning (Ch 3)


### Friday
**Prepare:** 

* Finish write all code from the lecture notes in a markdown file. 
  - One RMD file per chapter to help keep your notes organized. 
  
**In class:**

- Review How to submit [homework](admin/rubric.html)
* Finish data wrangling, munging, recoding, editing, cleaning.
* Start "_On Your Own_" problems for Ch 3 in a new markdown file 
    - Due Monday 2/1 midnight
    - Upload **the RMD** file ONLY BBlearn
    - Make sure it's named *userid_ch3.rmd* 
    


## Participation Opportunities

* Focus Question. The images I took from the Question focus activity done on
  Monday can be found in a [Google Slides presentation](https://drive.google.com/open?id=1VofDG-p_Df42qsYDg9HgaKgKs_7UfDeXofA0HJen8so) 
  in our shared Google Drive. Since we did not get to share very much during
  class I encourage you to look them over and see what questions other groups 
  came up with. You can contribute to this set of slides by either  
    - Adding a common theme in the questions that you notice. 
    - Providing rational as to why your group chose that question as your priority question. 
* Dicussion topics on the forum. Occasionally I will post topics for discussion on the
  course forum. They will have the tag `discussiontopic`. You are encouraged to read the
  post and use that forum as a place for your thoughts and discussion. 
  