---
title: "Week 2"
author: "MATH 459, Spring 2016"
date: " 2/1/16"
output: html_document
---
```{r results="asis", echo=FALSE}
source("C:/Github/MATH456/stylesheets/custom.R")
```
[[Week 1]](wk01.html) [[Week 3]](wk03.html)

## Announcements
**Homework Due:**  

* Homework 1 submission - Ch3 On Your Own problems.  
* [Solutions](notes/solutions/ch3_solutions.html) were posted on 1/31/16 around 4pm. 
* This homework will be reviewed for completeness and a **single** 
  random problem will be graded using the [Homework rubric](admin/rubric.html)

### Notes and Materials
* Lec 01: Preparing Data for Analysis [[PDF]](notes/lec01_data_prep.pdf)
[[HTML]](notes/lec01_data_prep.html)
[[RMD]](notes/lec01_data_prep.rmd)


## Experience (During Class)
### Monday
**Prepare:** Read Afifi Ch 4. Replicate code in lecture notes. 

* Data screening and transformations. 

### Wednesday
**Prepare:** Read Afifi Ch 5. Replicate code in lecture notes. 

* Selecting Appropriate Analysis
  

### Friday
* Consulting Experience: Introduction to Recruitment Database
* Finish Ch 4 & 5


## Looking Ahead
* Quiz on Monday. Ch 4 and Ch 5. Will come directly from the _On Your Own_ questions. 
* Starting Simple and Multiple Linear Regression next week. 

