---
title: "Week 3"
author: "MATH 456, Spring 2016"
date: " 02/08/16"
output: html_document
---
```{r results="asis", echo=FALSE}
source("C:/Github/MATH456/stylesheets/custom.R")
```
[[Schedule]](Schedule.html)  [[Week 2]](wk02.html) [[Week 4]](wk04.html)

## Announcements
* Quiz on Ch 4 & 5 on Monday
* Initial look at recruitment data due Wednesday


## Prepare 
* Complete Ch 4 & 5 HW. 
* Read Afifi Ch 6 & 7. 
* Download the raw [Lungraw](https://drive.google.com/open?id=0B83Z8_sNw3KPS29hZ1p3eXk4dmc) 
  data set, its [Codebook](https://drive.google.com/open?id=0B83Z8_sNw3KPNHpjZDRfaTR1LTQ) 
  from the Google Drive, and the [data management code file](data/dm_lung.Rmd) 
  to read in clean this data. 
* Replicate code in lecture notes for Simple Linear Regression. 

### Notes and Materials
* Lec 02: Linear Regression [[PDF]](notes/lec02_LinReg.pdf)[[HTML]](notes/lec02_LinReg.html)

## Experience
### Monday 2/8/16

* Quiz on material from Ch4 and Ch 5. 
* Review of Simple Linear Regression - Ch 6

### Wednesday 2/10/16
* 
* Finish Simple Linear Regression
    - Predictions
    - Assumptions
* Complete Ch 6 _On Your Own_ problems.  



### Friday
* Consulting Meeting: Dr. Jim Downing from College of Business
* Multiple Linear Regression - Introduction and Model Fitting

## Looking Ahead
* Variable selection

