---
title: "Week 4"
author: "MATH 456, Spring 2016"
date: ' 02/15/16'
output: pdf_document
---
```{r results="asis", echo=FALSE}
source("C:/Github/MATH456/stylesheets/custom.R")
```
[[Schedule]](Schedule.html)  [[Week 3]](wk03.html) [[Week 5]](wk05.html)

## Announcements
* Ch 6 Hw due on Sunday. 
* Consulting reflection assignment posted on BBLearn
* Revise and update your recruitment report. 

## Prepare 
* Read Afifi Ch 7. 
* Replicate code in lecture notes for Multiple Linear Regression. 

### Notes and Materials
* Lec 03: Multiple Linear Regression [[PDF]](notes/lec03_MultLinReg.pdf)[[HTML]](notes/lec03_MultLinReg.html)

## Experience
### Monday 2/15/16
* Multiple linear regression - Model fitting, predictions, interpretations

### Wednesday 2/17/16
* Multiple linear regression - Interactions & stratification

### Friday 2/19/16
* Consulting
    - Reflection on discussion boards due today
    - Comparative analysis of chosen variables needs to be worked on. 
    - Draft of report due next Friday 2/26
    - Dr Downing has OH 10-11:30 on Wednesday. Go ask him questions. 

* Handouts: Harrell Ch 1 & 2
* Writing models, reference coding and contrasts

## Looking Ahead
* BBLearn Quiz on Ch 7 - Due Monday @ 12. Topics include:
    - Writing and fitting linear models
    - Interpretation of coefficients
    - Model Diagnostics (also reference Harrel Ch 1)
    - Testing hypothesis using indicator variables and contrasts. 
* Splines, Missing Data


## Additional references
Regression Modeling Strategies (Harrell), e-book plus tons of supplemental materials including R code:  http://biostat.mc.vanderbilt.edu/wiki/Main/RmS




Not fully random links to other websites demonstrating regression modeling in R

* http://ww2.coastal.edu/kingw/statistics/R-tutorials/multregr.html
* http://www.gardenersown.co.uk/education/lectures/r/regression.htm 
* https://www.youtube.com/watch?v=q1RD5ECsSB0

