---
title: "Preliminaries and Logistics"
author: "MATH 456 - Spring 2016"
date: "1/25/16"
output: 
  html_document: 
    highlight: pygments
    theme: spacelab
---

# Science and Statistics
1. Scientific questions
2. Study Design
3. Data Collection
4. Data Entry
5. Data Management, Screening and Transformation
6. Multivariate Analysis

## Course Content Learning Outcomes
Upon successful completion of this course, students will be able to:  

* Translate a research question into an appropriate statistical analysis plan. 
* Prepare data for analysis by cleaning and transforming raw data. 
* Perform research in a reproducible manner. 
* Build a multivariate statistical model used to examine a real process. 
* Report the results of the analysis in plain language to a consulting client or collaborator. 

## Topics Covered

* Data cleaning
* Multiple linear regression
* Model building: Variable selection
* Dimension Reduction: Principle components and Factor Analysis
* Logistic regression
* Discriminant Analysis
* CART / Random Forests
* Predictive model building
* Missing Data

## Structure of this class
- Quasi flipped classroom. 
- Students read the book, review lecture notes and start coding prior to class. 
- Class time is devoted to reviewing the material, answering questions, working examples, discussing interpretations and limitations of methods learned.

## General schedule. 
- Monday  
    * Quiz or Homework submission. 
    * Lecture & Discussion.
- Wednesday  
    * Lecture & Discussion.
    * Start computer examples. 
- Friday   
    * Computer work day. 
    * Homework is assigned on Friday during class and due before class on the following Friday. 

Details on weekly topics can be found on the [schedule](./Schedule.html) on the course website.  

* Exam 1: Monday of Week 7
* Exam 2: Finals week
* Report 1: End of Week 7
* Report 2: End of Finals week

## Class materials
* Class website: http://norcalbiostat.github.io/MATH456
* First stop for all class materials. 
* The [syllabus](./Syllabus.html) covers course details such as grading, office hours and required materials. Spend 5 minutes to read that now. 
* Questions? 

## Computer Programming
* If you do not already have R & R Studio installed, check out a laptop. 
* Hands on Intro to R Studio and Markdown. 

## Prepare for Wednesday
* Read Afifi Ch 1-3
* Afifi problem 2.5 - Be prepared to share these with the class on Wednesday. Recommended to write up responses in Markdown. 


# Helpful web resources for learning R
* R Programming blog http://rprogramming.net
* Quick-R http://www.statmethods.net/
* Cookbook for R http://www.cookbook-r.com/
* R Examples Repository http://www.uni-kiel.de/psychologie/rexrepos/index.html
* R Bootcamp Data visualization tutorial http://norcalbiostat.github.io/R-Bootcamp/labs/Data_Visualization_Tutorial_Full.html

