\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
    \usepackage{xltxtra,xunicode}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{{#1}}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{{#1}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{{#1}}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\RegionMarkerTok}[1]{{#1}}
\newcommand{\ErrorTok}[1]{\textbf{{#1}}}
\newcommand{\NormalTok}[1]{{#1}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={MATH 456 - Spring 2016},
            pdftitle={Lec 08: Logistic Regression},
            colorlinks=true,
            citecolor=blue,
            urlcolor=blue,
            linkcolor=magenta,
            pdfborder={0 0 0}}
\urlstyle{same}  % don't use monospace font for urls
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\setcounter{secnumdepth}{0}

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}
  \title{Lec 08: Logistic Regression}
  \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \author{MATH 456 - Spring 2016}
  \preauthor{\centering\large\emph}
  \postauthor{\par}
  \date{}
  \predate{}\postdate{}



\begin{document}

\maketitle


Navbar: \href{../index.html}{{[}Home{]}}
\href{../Schedule.html}{{[}Schedule{]}}
\href{../data/Datasets.html}{{[}Data{]}} \href{../wk11.html}{{[}Week 11
Overview{]}} \href{../HW_Info.html}{{[}HW Info{]}}
\href{https://groups.google.com/forum/\#!forum/csuc_stat}{{[}Google
Group{]}}

\section{Assigned Reading and additional
references}\label{assigned-reading-and-additional-references}

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  Open Intro Section 8.4
\item
  Afifi Ch 12 (selected)
\item
  Article: When can odds ratios mislead?
  \url{http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1112884/}
\end{itemize}

-- Additional References

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  \url{http://www.ats.ucla.edu/stat/sas/faq/oratio.htm}
\end{itemize}

\section{Introduction}\label{introduction}

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  Logistic regression is a tool used to model a categorical outcome
  variable with two levels: Y = 1 if event, = 0 if no event.
\item
  Instead of modeling the outcome directly \(E(Y|X)\) as with linear
  regression, we model the probability of an event occurring:
  \(P(Y=1|X)\).
\end{itemize}

\subsection{Uses of Logistic Regression (Afifi
12.10)}\label{uses-of-logistic-regression-afifi-12.10}

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  Assess the impact selected covariates have on the probability of an
  outcome occurring.
\item
  Predict the likelihood / chance / probability of an event occurring
  given a certain covariate pattern.
\end{itemize}

\section{The Logistic Regression Model (Afifi
12.4)}\label{the-logistic-regression-model-afifi-12.4}

Let \(p_{i} = P(y_{i}=1)\).

The logistic model relates the probability of an event based on a linear
combination of X's.

\[
log\left(
\frac{p_{i}}{1-p_{i}}
\right) = \beta_{0} + \beta_{1}x_{1i} + \beta_{2}x_{2i} + \ldots + \beta_{p}x_{pi}
\]

Since the \emph{odds} are defined as the probability an event occurs
divided by the probability it does not occur: \((p/(1-p))\), the
function \(log\left(\frac{p_{i}}{1-p_{i}}\right)\) is also known as the
\emph{log odds}, or more commonly called the \textbf{\emph{logit}}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p <-}\StringTok{ }\KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DataTypeTok{by=}\NormalTok{.}\DecValTok{01}\NormalTok{)}
\NormalTok{logit.p <-}\StringTok{ }\KeywordTok{log}\NormalTok{(p/(}\DecValTok{1}\NormalTok{-p))}
\KeywordTok{qplot}\NormalTok{(logit.p, p, }\DataTypeTok{geom=}\StringTok{"line"}\NormalTok{, }\DataTypeTok{xlab =} \StringTok{"logit(p)"}\NormalTok{, }\DataTypeTok{main=}\StringTok{"The logit transformation"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{lec08_LogisticRegression_files/figure-latex/unnamed-chunk-3-1.pdf}

This in essence takes a binary outcome 0/1 variable, turns it into a
continuous probability (which only has a range from 0 to 1) Then the
logit(p) has a continuous distribution ranging from \(-\infty\) to
\(\infty\), which is the same form as a Multiple Linear Regression
(continuous outcome modeled on a set of covariates)

\subsection{Modeling the probability of an
event.}\label{modeling-the-probability-of-an-event.}

Back solving the logistic model for
\(p_{i} = e^{\beta X} / (1+e^{\beta X})\):

\[
p_{i} = \frac{e^{\beta_{0} + \beta_{1}x_{1i} + \beta_{2}x_{2i} + \ldots + \beta_{p}x_{pi}}}
{1 + e^{\beta_{0} + \beta_{1}x_{1i} + \beta_{2}x_{2i} + \ldots + \beta_{p}x_{pi}}}
\]

\subsection{Logistic Regression via GLM in
R}\label{logistic-regression-via-glm-in-r}

A logistic regression model can be fit in R using the \texttt{glm()}
function. GLM stands for Generalized Linear Model. GLM's can fit an
entire \emph{family} of distributions and can be thought of as
\(E(Y|X) = C(X)\) where \(C\) is a \textbf{link} function that relates
\(Y\) to \(X\).

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  Linear regression: C = Identity function (no change)
\item
  Logistic regression: C = logit function
\item
  Poisson regression: C = log function
\end{itemize}

The outcome \(y\) is a 0/1 Bernoulli random variable. The sum of a
vector of Bernoulli's (\(\sum_{i=1}^{n}y_{i}\)) has a Binomial
distribution. When we specify that \texttt{family = "binomial"} the
\texttt{glm()} function auto-assigns a ``logit'' link function. See
\texttt{?family} for more information on this.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{glm}\NormalTok{(y ~}\StringTok{ }\NormalTok{x1 +}\StringTok{ }\NormalTok{x2 +}\StringTok{ }\NormalTok{x3, }\DataTypeTok{data=}\NormalTok{DATA, }\DataTypeTok{family=}\StringTok{"binomial"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\section{Example: Gender effects on
Depression}\label{example-gender-effects-on-depression}

Read in the depression data and recode sex to be an indicator of being
male.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{depress <-}\StringTok{ }\KeywordTok{read.delim}\NormalTok{(}\StringTok{"C:/GitHub/MATH456/data/depress_030816.txt"}\NormalTok{)}
\KeywordTok{names}\NormalTok{(depress) <-}\StringTok{ }\KeywordTok{tolower}\NormalTok{(}\KeywordTok{names}\NormalTok{(depress)) }\CommentTok{# make all variable names lower case. }
\NormalTok{depress$sex <-}\StringTok{ }\NormalTok{depress$sex -}\DecValTok{1} \CommentTok{# Refactor to match book table.}
\end{Highlighting}
\end{Shaded}

\subsection{Using a two-way table.}\label{using-a-two-way-table.}

Examine the two-way table of gender by depression and calculate the Odds
Ratio for depression and gender.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(depress$sex, depress$cases, }\DataTypeTok{dnn =} \KeywordTok{c}\NormalTok{(}\StringTok{"Gender"}\NormalTok{, }\StringTok{"Depression"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       Depression
## Gender   0   1
##      0 101  10
##      1 143  40
\end{verbatim}

Recall that the \texttt{epi.2by2} function in the \texttt{epiR} package
required the (1,1) cell to be in the upper left corner. That is not
default table orientation for R. So here is a helper function
\texttt{rotate()} that I found on
\href{http://stackoverflow.com/questions/16496210/rotate-a-matrix-in-r}{StackOverflow}
that will rotate the matrix to the proper orientation.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rotate <-}\StringTok{ }\NormalTok{function(x) }\KeywordTok{t}\NormalTok{(}\KeywordTok{apply}\NormalTok{(}\KeywordTok{t}\NormalTok{(}\KeywordTok{apply}\NormalTok{(x, }\DecValTok{2}\NormalTok{, rev)), }\DecValTok{2}\NormalTok{, rev))}
\end{Highlighting}
\end{Shaded}

Create the table object, rotate it (to confirm it works), and call
\texttt{epi.2by2} to calculate the OR and corresponding CI.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(epiR)}
\NormalTok{dep_sex_xtab <-}\StringTok{ }\KeywordTok{table}\NormalTok{(depress$sex, depress$cases)}
\KeywordTok{rotate}\NormalTok{(dep_sex_xtab)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    
##      1   0
##   1 40 143
##   0 10 101
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{epi.2by2}\NormalTok{(}\KeywordTok{rotate}\NormalTok{(dep_sex_xtab))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Outcome +    Outcome -      Total        Inc risk *
## Exposed +           40          143        183             21.86
## Exposed -           10          101        111              9.01
## Total               50          244        294             17.01
##                  Odds
## Exposed +       0.280
## Exposed -       0.099
## Total           0.205
## 
## Point estimates and 95 % CIs:
## -------------------------------------------------------------------
## Inc risk ratio                               2.43 (1.26, 4.65)
## Odds ratio                                   2.83 (1.35, 5.91)
## Attrib risk *                                12.85 (4.83, 20.86)
## Attrib risk in population *                  8.00 (1.16, 14.84)
## Attrib fraction in exposed (%)               58.78 (20.92, 78.52)
## Attrib fraction in population (%)            47.03 (10.63, 68.60)
## -------------------------------------------------------------------
##  X2 test statistic: 8.082 p-value: 0.004
##  Wald confidence limits
##  * Outcomes per 100 population units
\end{verbatim}

Females have 2.83 times the odds of being depressed compared to males
(95\% CI 1.35, 5.91).

\subsection{Using Logistic Regression}\label{using-logistic-regression}

We will come to the same conclusion by running a logistic regression
model,

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dep_sex_model <-}\StringTok{ }\KeywordTok{glm}\NormalTok{(cases ~}\StringTok{ }\NormalTok{sex, }\DataTypeTok{data=}\NormalTok{depress, }\DataTypeTok{family=}\StringTok{"binomial"}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(dep_sex_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = cases ~ sex, family = "binomial", data = depress)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.7023  -0.7023  -0.4345  -0.4345   2.1941  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  -2.3125     0.3315  -6.976 3.04e-12 ***
## sex           1.0386     0.3767   2.757  0.00583 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 268.12  on 293  degrees of freedom
## Residual deviance: 259.40  on 292  degrees of freedom
## AIC: 263.4
## 
## Number of Fisher Scoring iterations: 5
\end{verbatim}

and exponentiating the coefficients.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\KeywordTok{coef}\NormalTok{(dep_sex_model))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)         sex 
##   0.0990099   2.8251748
\end{verbatim}

The Odds Ratio for depression among Females compared to males is 2.83.

\subsection{Confidence Intervals}\label{confidence-intervals}

The OR is \textbf{not} a linear function of the \(x's\), but \(\beta\)
is. This means that a CI for the OR is created by calculating a CI for
\(\beta\), and then exponentiating the endpoints. A 95\% CI for the OR
can be calculated as:

\[e^{\hat{\beta} \pm 1.96 SE_{\beta}} \]

In R this looks like:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\KeywordTok{confint}\NormalTok{(dep_sex_model))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  2.5 %    97.5 %
## (Intercept) 0.04843014 0.1801265
## sex         1.39911056 6.2142384
\end{verbatim}

\section{Multiple Logistic Regression (Afifi 12.5,
12.6)}\label{multiple-logistic-regression-afifi-12.5-12.6}

Just like multiple linear regression, additional predictors are simply
included in the model using a \texttt{+} symbol.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mvmodel <-}\StringTok{ }\KeywordTok{glm}\NormalTok{(cases ~}\StringTok{ }\NormalTok{age +}\StringTok{ }\NormalTok{income +}\StringTok{ }\NormalTok{sex, }\DataTypeTok{data=}\NormalTok{depress, }\DataTypeTok{family=}\StringTok{"binomial"}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(mvmodel)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = cases ~ age + income + sex, family = "binomial", 
##     data = depress)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.0249  -0.6524  -0.5050  -0.3179   2.5305  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)   
## (Intercept) -0.67646    0.57881  -1.169  0.24253   
## age         -0.02096    0.00904  -2.318  0.02043 * 
## income      -0.03656    0.01409  -2.595  0.00946 **
## sex          0.92945    0.38582   2.409  0.01600 * 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 268.12  on 293  degrees of freedom
## Residual deviance: 247.54  on 290  degrees of freedom
## AIC: 255.54
## 
## Number of Fisher Scoring iterations: 5
\end{verbatim}

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  The sign of the \(\beta\) coefficients can be interpreted in the same
  manner as with linear regression.
\item
  The odds of being depressed are less if the respondent has a higher
  income and is older, and higher if the respondant is female.
\end{itemize}

\subsubsection{OR interpretation}\label{or-interpretation}

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  The OR provides a directly understandable statistic for the
  relationship between \(y\) and a specific \(x\) given all other
  \(x\)'s in the model are fixed.
\item
  For a continuous variable X with slope coefficient \(\beta\), the
  quantity \(e^{b}\) is interpreted as the ratio of the odds for a
  person with value (X+1) relative to the odds for a person with value
  X.
\item
  \(exp(kb)\) is the incremental odds ratio corresponding to an increase
  of \(k\) units in the variable X, assuming that the values of all
  other X variables remain unchanged.
\end{itemize}

\textbf{Binary variables} Calculate the Odds Ratio of depression for
women compared to men.

\textbf{WRITE OUT THE MODEL}
\[log(odds) = -0.676 - 0.02096*age - .03656*income + 0.92945*gender\]

\[ OR = \frac{Odds (Y=1|F)}{Odds (Y=1|M)} \]

Write out the equations for men and women separately.
\[ = \frac{e^{-0.676 - 0.02096*age - .03656*income + 0.92945(1)}}
          {e^{-0.676 - 0.02096*age - .03656*income + 0.92945(0)}}\]

Applying rules of exponents to simplify.
\[ = \frac{e^{-0.676}e^{- 0.02096*age}e^{- .03656*income}e^{0.92945(1)}}
          {e^{-0.676}e^{- 0.02096*age}e^{- .03656*income}e^{0.92945(0)}}\]

\[ = \frac{e^{0.92945(1)}}
          {e^{0.92945(0)}}\]

\[ = e^{0.92945} \]

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(.}\DecValTok{92945}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.533116
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\KeywordTok{coef}\NormalTok{(mvmodel)[}\DecValTok{4}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      sex 
## 2.533112
\end{verbatim}

The odds of a female being depressed are 2.53 times greater than the
odds for Males after adjusting for the linear effects of age and income
(p=.016).

\textbf{Continuous variables}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\KeywordTok{coef}\NormalTok{(mvmodel))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)         age      income         sex 
##   0.5084157   0.9792605   0.9640969   2.5331122
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\KeywordTok{confint}\NormalTok{(mvmodel))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                 2.5 %    97.5 %
## (Intercept) 0.1585110 1.5491849
## age         0.9615593 0.9964037
## income      0.9357319 0.9891872
## sex         1.2293435 5.6586150
\end{verbatim}

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  The Adjusted odds ratio (AOR) for increase of 1 year of age is 0.98
  (95\%CI .96, 1.0)
\item
  How about a 10 year increase in age?
  \(e^{10*\beta_{age}} = e^{-.21} = .81\)
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\DecValTok{10}\NormalTok{*}\KeywordTok{coef}\NormalTok{(mvmodel)[}\DecValTok{2}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       age 
## 0.8109285
\end{verbatim}

with a confidence interval of

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{round}\NormalTok{(}\KeywordTok{exp}\NormalTok{(}\DecValTok{10}\NormalTok{*}\KeywordTok{confint}\NormalTok{(mvmodel)[}\DecValTok{2}\NormalTok{,]),}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  2.5 % 97.5 % 
##  0.676  0.965
\end{verbatim}

Controlling for gender and income, an individual has 0.81 (95\% CI 0.68,
0.97) times the odds of being depressed compared to someone who is 10
years younger than them.

\subsection{CAUTION}\label{caution}

Consider a hypothetical example where the probability of death is .4 for
males and .6 for females.

The odds of death for males is \texttt{.4/(1-.4)} = 0.67. The odds of
death for females is \texttt{.6/(1-.6)} = 1.5.

The Odds Ratio of death for females compared to males is
\texttt{1.5/.66} = 2.27.

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  If you were to say that females were 2.3 times as likely to die
  compare to males, you wouldn't necessarily translate that to a 40\% vs
  60\% chance.
\end{itemize}

\subsection{Probability
Interpretation}\label{probability-interpretation}

For the above model of depression on age, income and gender the
probability of depression is: \[
P(depressed) = \frac{e^{-0.676 - 0.02096*age - .03656*income + 0.92945*gender}}
{1 + e^{-0.676 - 0.02096*age - .03656*income + 0.92945*gender}}
\]

Let's compare the probability of being depressed for males and females
separately, while holding age and income constant at their average
value.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{depress %>%}\StringTok{ }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{age=}\KeywordTok{mean}\NormalTok{(age), }\DataTypeTok{income=}\KeywordTok{mean}\NormalTok{(income))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        age   income
## 1 44.41497 20.57483
\end{verbatim}

Plug the coefficient estimates and the values of the variables into the
equation and calculate. \[
P(depressed|Female) = \frac{e^{-0.676 - 0.02096(44.4) - .03656(20.6) + 0.92945(1)}}
{1 + e^{-0.676 - 0.02096(44.4) - .03656(20.6) + 0.92945(1)}}
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{XB.f <-}\StringTok{ }\NormalTok{-}\FloatTok{0.676} \NormalTok{-}\StringTok{ }\FloatTok{0.02096}\NormalTok{*(}\FloatTok{44.4}\NormalTok{) -}\StringTok{ }\NormalTok{.}\DecValTok{03656}\NormalTok{*(}\FloatTok{20.6}\NormalTok{) +}\StringTok{ }\FloatTok{0.92945}
\KeywordTok{exp}\NormalTok{(XB.f) /}\StringTok{ }\NormalTok{(}\DecValTok{1}\NormalTok{+}\KeywordTok{exp}\NormalTok{(XB.f))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1930504
\end{verbatim}

\[
P(depressed|Male) = \frac{e^{-0.676 - 0.02096(44.4) - .03656(20.6) + 0.92945(0)}}
{1 + e^{-0.676 - 0.02096(44.4) - .03656(20.6) + 0.92945(0)}}
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{XB.m <-}\StringTok{ }\NormalTok{-}\FloatTok{0.676} \NormalTok{-}\StringTok{ }\FloatTok{0.02096}\NormalTok{*(}\FloatTok{44.4}\NormalTok{) -}\StringTok{ }\NormalTok{.}\DecValTok{03656}\NormalTok{*(}\FloatTok{20.6}\NormalTok{)}
\KeywordTok{exp}\NormalTok{(XB.m) /}\StringTok{ }\NormalTok{(}\DecValTok{1}\NormalTok{+}\KeywordTok{exp}\NormalTok{(XB.m))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.08629312
\end{verbatim}

The probability for a 44.4 year old female who makes \$20.6k annual
income has a 0.19 probability of being depressed. The probabilty of
depression for a male of equal age and income is 0.86.

\section{Logistic models with interaction terms (Afifi
12.7)}\label{logistic-models-with-interaction-terms-afifi-12.7}

\textbf{This section follows the book very closely so minimal notes are
presented}

The inclusion of an interaction is necessary if the effect of an
independent variable depends on the level of another independent
variable.

\paragraph{Example: The relationsihp between income, employment status
and
depression.}\label{example-the-relationsihp-between-income-employment-status-and-depression.}

Here I create the binary indicators of lowincome and underemployed as
described in the textbook. In each case I ensure that missing data is
retained.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{depress$lowincome <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(depress$income <}\StringTok{ }\DecValTok{10}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\NormalTok{depress$lowincome <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(depress$income), }\OtherTok{NA}\NormalTok{, depress$lowincome)}

\NormalTok{depress$underemployed <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(depress$employ %in%}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{), }\DecValTok{1}\NormalTok{, }\DecValTok{0} \NormalTok{)}
\NormalTok{depress$underemployed <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(depress$employ) |}\StringTok{ }\NormalTok{depress$employ==}\DecValTok{7}\NormalTok{, }\OtherTok{NA}\NormalTok{, depress$underemployed)}
\KeywordTok{table}\NormalTok{(depress$underemployed, depress$employ, }\DataTypeTok{useNA=}\StringTok{"always"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       
##          1   2   3   4   5   6   7 <NA>
##   0    167   0   0  38  27   2   0    0
##   1      0  42  14   0   0   0   0    0
##   <NA>   0   0   0   0   0   0   4    0
\end{verbatim}

The \textbf{Main Effects} model assumes that the effect of income on
depression is indpendent of employment status, and the effect of
employment status on depression is independent of income.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{me_model <-}\StringTok{ }\KeywordTok{glm}\NormalTok{(cases ~}\StringTok{ }\NormalTok{lowincome +}\StringTok{ }\NormalTok{underemployed, }\DataTypeTok{data=}\NormalTok{depress, }\DataTypeTok{family=}\StringTok{"binomial"}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(me_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = cases ~ lowincome + underemployed, family = "binomial", 
##     data = depress)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.9227  -0.5894  -0.5195  -0.5195   2.0345  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(>|z|)    
## (Intercept)    -1.9345     0.2259  -8.563  < 2e-16 ***
## lowincome       0.2723     0.3377   0.806  0.42004    
## underemployed   1.0285     0.3487   2.949  0.00318 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 263.46  on 289  degrees of freedom
## Residual deviance: 254.86  on 287  degrees of freedom
##   (4 observations deleted due to missingness)
## AIC: 260.86
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

To formally test whether an interaction term is necessary, we add the
interaction term into the model and assess whether the coefficient for
the interaction term is significantly different from zero.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(}\KeywordTok{glm}\NormalTok{(cases ~}\StringTok{ }\NormalTok{lowincome +}\StringTok{ }\NormalTok{underemployed +}\StringTok{ }\NormalTok{lowincome*underemployed, }\DataTypeTok{data=}\NormalTok{depress, }\DataTypeTok{family=}\StringTok{"binomial"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = cases ~ lowincome + underemployed + lowincome * 
##     underemployed, family = "binomial", data = depress)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.3537  -0.5701  -0.5701  -0.4783   2.1093  
## 
## Coefficients:
##                         Estimate Std. Error z value Pr(>|z|)    
## (Intercept)              -1.7346     0.2214  -7.835  4.7e-15 ***
## lowincome                -0.3756     0.4349  -0.864  0.38780    
## underemployed             0.3175     0.4520   0.702  0.48238    
## lowincome:underemployed   2.1981     0.7888   2.787  0.00533 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 263.46  on 289  degrees of freedom
## Residual deviance: 246.63  on 286  degrees of freedom
##   (4 observations deleted due to missingness)
## AIC: 254.63
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\subsection{Confouding and Effect
Modification}\label{confouding-and-effect-modification}

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  \textbf{Confounder}: A covariate that is associated with both the
  outcome and the risk factor.
\item
  \textbf{Effect Modifier}: A covariate that modifies the effect a
  second covariate has on the outcome.
\end{itemize}

\section{Refining and evaluating logistic
regression}\label{refining-and-evaluating-logistic-regression}

\section{Going further}\label{going-further}

When your outcome has more than one level and you want to build a
regression model to assess the impact a specific variable (or set of
variables) has on the levels of this outcome variable, you would need to
turn to more generalized linear models such as:

\begin{itemize}
\item
  Multinomial distribution for a nominal outcome

  \begin{itemize}
  \itemsep1pt\parskip0pt\parsep0pt
  \item
    \url{http://www.ats.ucla.edu/stat/r/dae/mlogit.htm}
  \end{itemize}
\item
  Ordinal logistic regression
\item
  \url{http://www.r-bloggers.com/how-to-perform-a-logistic-regression-in-r/}
\end{itemize}

\href{lec08_LogisticRegression.html}{{[}top{]}}

\section{On Your Own}\label{on-your-own}

\subparagraph{On Your Own}\label{on-your-own-1}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\itemsep1pt\parskip0pt\parsep0pt
\item
  What does an Odds Ratio of 1 signify? What if the OR \textless{} 1?
  What about when OR \textgreater{} 1? You can use a pair of example
  variables such as X=gender and y=death if it helps you explain.
\item
  Afifi 12.9 (a-c)
\item
  Afifi 12.14
\item
  Afifi 12.15
\item
  Afifi 12.16
\item
  Afifi 12.17
\item
  Afifi 12.18
\item
  Afifi 12.23
\end{enumerate}

\end{document}
