---
title: "List of Datasets used"
output: 
  html_document: 
    theme: journal
---

```{r include = FALSE}
library(dplyr)
library(stringr)
library(readr)
```

```{r results="asis", echo=FALSE}
source("C:/Github/MATH456/stylesheets/custom.R")
```

Navbar: [[Home]](../index.html) [[Schedule]](../schedule.html)


```{r include = FALSE}
rawdat <- read_csv("Datasets.csv")

# location of files
cdat  <- rawdat %>% mutate(dataloc = paste("data/", filename, sep=""), 
                           codeloc = paste("data/", codebook, sep=""), 
                           dmloc   = paste("data/", dm, sep=""),
                           Updated = format(file.info(dm)$mtime), "%m-%d-%y")

# Add link to the data file, codebook, data management code file
cdat2 <- cdat %>% mutate(File = paste('<a href="', cdat$dataloc, '">', cdat$filename, '</a>', sep=""), 
                         Codebook = ifelse(is.na(codebook), "-", paste('<a href="', codeloc, '">', codebook, '</a>', sep="")), 
                         `Data Management` = ifelse(is.na(dm), "-", paste('<a href="', dmloc, '">', dm, '</a>', sep="")), 
                         Notes = ifelse(is.na(Notes), "-",Notes),
                         Updated = ifelse(is.na(Updated), "-",Updated))

# Select vars to display
clean <- cdat2 %>% select(Data, File, Codebook, `Data Management`, Updated, Notes)

```

<!-- unholy hack to make following two tables less wide and the same wide -->
<style type="text/css">
table {
   max-width: 50%;
}
</style>
All data sets listed are in their raw format. Codebooks and data management
files are supplied as available. The **Last Updated** column represents the
last time the data management file was edited. You should ensure that
you always have the most up to date data management file. 

```{r results = 'asis', echo = FALSE}
knitr::kable(clean)
```
